### ISSUE TITLE
Console app wait on operations to finish

### ISSUE THREAD

**Issue by malhal** [BennyKJohnson/OpenCloudKit#5]
So I followed the example in the readme, but I had an issue that the program ended before the operation completion was called. I fixed it by placing a CFRunLoopRun() at the bottom of my code, I was wondering what your thoughts are on dealing with this?

**Comment by BennyKJohnson** [comment]
In order to receive callbacks on any asynchronous functions, some type of run loop must be in place.
OpenCloudKit is mainly designed to be used with a Swift web framework such as [Vapor](https://vapor.codes) or [Perfect](https://www.perfect.org) which implement their own run loops. However you can use it by itself using the `CFRunLoopRun()` as you mentioned.
